name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_linux_64:
    runs-on: ubuntu-latest

    env:
      GARRYSMOD_COMMON: ${{ github.workspace }}/garrysmod_common

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies (Premake5)
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta4/premake-5.0.0-beta4-linux.tar.gz
        tar -xvf premake-5.0.0-beta4-linux.tar.gz
        chmod +x premake5

    - name: Clone garrysmod_common
      run: |
        git clone https://github.com/danielga/garrysmod_common --recursive --branch=x86-64-support-sourcesdk $GARRYSMOD_COMMON

    - name: Generate makefiles with Premake
      run: |
        ./premake5 gmake

    - name: Build the project
      run: |
        cd projects/linux/gmake
        make config=releasewithsymbols_x86_64
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_xconsole_linux64.dll
        path: ${{ github.workspace }}/projects/linux/gmake/x86_64/ReleaseWithSymbols/gmsv_xconsole_linux64.dll
              
  build_linux:
    runs-on: ubuntu-latest

    env:
      GARRYSMOD_COMMON: ${{ github.workspace }}/garrysmod_common

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies (Premake5 & GCC Multilib)
      run: |
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-beta4/premake-5.0.0-beta4-linux.tar.gz
        tar -xvf premake-5.0.0-beta4-linux.tar.gz
        chmod +x premake5
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib

    - name: Clone garrysmod_common
      run: |
        git clone https://github.com/danielga/garrysmod_common --recursive $GARRYSMOD_COMMON

    - name: Generate makefiles with Premake
      run: |
        sed -i 's/PROJECT_GENERATOR_VERSION = 3/PROJECT_GENERATOR_VERSION = 2/' premake5.lua
        ./premake5 gmake

    - name: Build the project
      run: |
        cd projects/linux/gmake
        make
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmsv_xconsole_linux.dll
        path: ${{ github.workspace }}/projects/linux/gmake/x86/ReleaseWithSymbols/gmsv_xconsole_linux.dll
